name: Rebuild

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check-for-rebuild:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Get latest Nginx stable version
        id: nginx
        run: |
          VERSION=$(curl -s https://registry.hub.docker.com/v2/repositories/library/nginx/tags/?page_size=100 \
            | jq -r '.results[].name' \
            | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' \
            | sort -V \
            | tail -n1)
          echo "Latest stable version: $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Check if image with version already exists
        id: check
        run: |
          if docker manifest inspect ${{ secrets.DOCKERHUB_USERNAME }}/nginx-h5bp:${{ steps.nginx.outputs.version }} > /dev/null 2>&1; then
            echo "Image already exists. Skipping build."
            echo "build_needed=false" >> $GITHUB_OUTPUT
          else
            echo "New version. Proceeding to build."
            echo "build_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Trigger build
        if: steps.check.outputs.build_needed == 'true'
        run: gh workflow run release.yaml
